theme: jekyll-theme-minimal
title: IARG - <br>Image Analysis Reading Group
description: Discusses topics related to image and signal analysis, both methods and applications.  Special interests in machine learning approaches and medical image analysis.
