theme: jekyll-theme-cayman
title: Image Analysis Reading Group
description: A group of people meeting at Macquarie University's Department of Computing to discuss topics related to image analysis and applications.
